### ISSUE TITLE
关于训练自己数据集的问题

### ISSUE THREAD

**Issue by cendelian** [Sierkinhane/crnn_chinese_characters_rec#260]
你好，
我需要训练自己的数据集，

1.
关于txt格式，我理解如下：
’img_name   标注‘
比如：
img_0.jpg	福
img_1.jpg	空调维修保养
img_2.jpg	空调移机保养
img_3.jpg	久斯台球会所
请问我理解正确吗？

2. 训练自己的数据集出现很多比如其中之一keyError：‘o’
请问该怎么解决？

3.360w里面txt后面的标注都是数字，这个是怎么翻译的呢？
比如下面这个：
20456343_4045240981.jpg 89 201 241 178 19 94 19 22 26 656
20457281_3395886438.jpg 120 1061 2 376 78 249 272 272 120 1061

空格后面的数据代表什么意思？怎么对应是那些字符？

谢谢！！！

**Comment by chichuhu** [comment]
训练自己的数据及就是这样标注，不过配置文件要选OWN.yaml
是通过char_std_5990.txt翻译的

**Comment by cendelian** [comment]
> 训练自己的数据及就是这样标注，不过配置文件要选OWN.yaml
> 是通过char_std_5990.txt翻译的
我选的就是OWN.yaml，并且配置了自己的路径，如下：
```
DATASET:
  DATASET: OWN
  ROOT: "/data2/deliancen/workpace/OCR/Data/Synthetic_Chinese_String_Dataset/images"
  JSON_FILE: {'train': 'lib/dataset/txt/train_own.txt', 'val': 'lib/dataset/txt/test_own.txt'}
  SCALE_FACTOR: 0.25
  ROT_FACTOR: 30
  STD: 0.193
  MEAN: 0.588
  ALPHABETS: ''
```

启动训练会发生很多keyError，比如下面
keyError：‘o’
请问怎么解决这写keyError？是建立自己数据集对应的字典？替换掉config/alphabets.py里面的内容还是添加进去？
